# Data in GCTA format
in_sumstats: /nfs/users/nfs_e/em21/otcoregen/em21/uk_biobank_stanford/data/clean/{study}.nealeUKB_20170915.assoc.clean.tsv.gz
# Reference sample for calucling LD matrix
ref_panel: /nfs/users/nfs_e/em21/otcoregen/em21/reference_data_download/uk10k/2_process/test_plink/{chrom}.ALSPAC_TWINSUK.maf01.beagle.anno_updated.csq.shapeit.20131101
# Pheno summary file to calc proportion of cases from
pheno_file: /nfs/users/nfs_e/em21/otcoregen/em21/uk_biobank_stanford/data/phenosummary_final_11898_18597.fixed.tsv

# # # Data in GCTA format
# in_sumstats: /Users/em21/Projects/finemapping/data/{study}.nealeUKB_20170915.assoc.clean.tsv.gz
# # Reference sample for calucling LD matrix
# # ref_panel: /Users/em21/Projects/reference_data/1000Genomes_phase3/plink_format/EUR/1kg_p3.20130502.EUR.{chrom}
# ref_panel: /Users/em21/Projects/finemapping/data/uk10k_ld/{chrom}.ALSPAC_TWINSUK.maf01.beagle.anno_updated.csq.shapeit.20131101
# # Pheno summary file to calc proportion of cases from
# pheno_file: /Users/em21/Projects/uk_biobank_stanford/data/phenosummary_final_11898_18597.fixed.tsv

# Global args
chroms: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
# chroms: [6, 22]
min_cases: 100 # Minimum number of cases
n_cores_cojo: 4
n_cores_finemap: 4
exclude_MHC: True

# Distance based clumping
clump_dist: 500  # Distance (kb) either side of index to clump by
clump_pval: 1e-5 # Maximum p-value for clumping output

# GCTA cojo select parameters
cojo_colin: 0.9   # Don't include SNPs that are colinear with an already selected SNP
cojo_wind:  10000 # (Kb) Assume SNPs outside window are in linkage equilibrium
cojo_p:     5e-8  # P-value for declaring signficant
cojo_maf:   0.01  # Min minor allele freq

# Identifying nearby loci to run conditional analysis for
cond_multisig_wind: 500 # (Kb) Loci within this distance of each other will have sum stats recomputed using conditional analysis

# GCTA cojo conditional parameters
cond_extract_wind: 500  # (Kb) Extract variants +- this window for finemapping
cond_maf: 0.01          # Min minor allele freq
