# Input files
analysis_config_file: configs/analysis.config.yaml
manifest_file: configs/manifest.json
# eur_ld: input/ld/EUR.{chrom}.1000Gp3.20130502 # This will go in the manifest instead
gwas_sumstats_dir: input/gwas
mol_sumstats_dir: input/molecular_qtl
results_dir: output
temp_dir: tmp

# Configure whether completed studies should be skiped
skip_existing: True
# skip_existing: False
existing_results_dir: 'output_completed' # Location of output that contains results to skip

# Parallel
n_cores: 3
